param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.4\common\bin\cspybat" -f "C:\Users\nxa16038\Desktop\work\RT\RT1170\SDK\SDK_2.8.1_MIMXRT1170-EVK_PRC3_minimal\boards\evkmimxrt1170\driver_examples\semc\sdram\cm7\iar\settings\semc_cm7.debug.general.xcl" --backend -f "C:\Users\nxa16038\Desktop\work\RT\RT1170\SDK\SDK_2.8.1_MIMXRT1170-EVK_PRC3_minimal\boards\evkmimxrt1170\driver_examples\semc\sdram\cm7\iar\settings\semc_cm7.debug.driver.xcl" 
}
else
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.4\common\bin\cspybat" -f "C:\Users\nxa16038\Desktop\work\RT\RT1170\SDK\SDK_2.8.1_MIMXRT1170-EVK_PRC3_minimal\boards\evkmimxrt1170\driver_examples\semc\sdram\cm7\iar\settings\semc_cm7.debug.general.xcl" --debug_file=$debugfile --backend -f "C:\Users\nxa16038\Desktop\work\RT\RT1170\SDK\SDK_2.8.1_MIMXRT1170-EVK_PRC3_minimal\boards\evkmimxrt1170\driver_examples\semc\sdram\cm7\iar\settings\semc_cm7.debug.driver.xcl" 
}
